### ISSUE TITLE
This doesn't work if installed with Fisher

### ISSUE THREAD

**Issue by gm0re** [jukben/z#1]
Trying to use z, it says the command doesn't exist.

When it looks for the z.sh it does it here:
`  set -lx Z_SCRIPT_PATH /usr/local/etc/profile.d/z.sh `

But that's not where `fisher` installs the z.sh.

Any idea where the z.sh is installed? Thanks!

**Comment by jukben** [comment]
Hey! Did you follow the readme? If I remember correctly – this is just wrapper, so please install Z with brew.

> brew install z
> fisher add jukben/z

**Comment by jukben** [comment]
Feel free to reopen if it's still the issue
