### ISSUE TITLE
Use brew prefix for base path

### ISSUE THREAD

**Issue by pardahlman** [jukben/z#3]
Great work on this. I haven't used fish or brew that much, so perhaps I'm wrong here... but, when installing this plugin I get the following error when invoking `z`

```
> z
bash: line 3: _z: command not found
cd: The directory 'bash: line 2: /opt/homebrew/etc/profile.d/z.sh: No such file or directory' does not exist
```

I believe this is due to the fact that the path to brew is assumed to be `/opt/homebrew`. The default directory on linux is `/home/linuxbrew` (see [the documentation](https://docs.brew.sh/Homebrew-on-Linux#install)).

If I update the line to derive brew's base path from `brew --prefix` it works as expected:

```fish
set -lx Z_SCRIPT_PATH "$(brew --prefix)/etc/profile.d/z.sh"
```

I believe this will work for users with custom prefixes as well.

**Comment by jukben** [comment]
Hey, glad it works for you! Would you mind sending PR for it? 🙏

**Comment by pardahlman** [comment]
Here it is. I tried it on my Ubuntu installation using the following command

```
fisher install pardahlman/z@brew-prefix
```

Feel free to try it out on your setup to verify that it works there, too.
